---
title: "Clase 7 de Métodos Numéricos    01-10-2025"
author: "Diana Laura Pais Felipe     Matrícula:23-002-0030"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: show
    theme: bootstrap
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Gauss-Seidel

```{r}
A <- matrix(c(4, -1, 0, 0, 0,
             -1, 4, -1, 0, 0,
             0, -1, 4, -1, 0,
             0, 0, -1, 4, -1,
             0, 0, 0, -1, 4),
nrow = 5, byrow = TRUE)
b <- c(1, 2, 3, 4, 5)
(A)
(b)
```


```{r}
x <- rep(0, 5) # x^(0)=(0,0,0,0,0)
cat("x^(0)=",paste(sprintf("%.8f",x), collapse=", "), "\n")
```


### Iteración 1

```{r}
x_old <- x
cat("\nIteración 1\n")

```



```{r}
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(1) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
```

```{r}
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(1) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
```

```{r}
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(1) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
```

```{r}
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(1) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
```

```{r}
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(1) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
```

```{r}
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(1) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```

### Iteración 2

```{r}
x_old <- x
cat("\nIteración 2\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(2) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(2) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(2) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(2) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(2) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(2) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```

### Iteración 3

```{r}
x_old <- x
cat("\nIteración 3\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(3) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(3) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(3) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(3) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(3) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(3) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 4

```{r}
x_old <- x
cat("\nIteración 4\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(4) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(4) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(4) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(4) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(4) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(4) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 5

```{r}
x_old <- x
cat("\nIteración 5\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(5) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(5) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(5) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(5) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(5) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(5) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 6

```{r}
x_old <- x
cat("\nIteración 6\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(6) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(6) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(6) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(6) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(6) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(6) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 7

```{r}
x_old <- x
cat("\nIteración 7\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(7) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(7) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(7) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(7) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(7) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(7) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 8

```{r}
x_old <- x
cat("\nIteración 8\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(8) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(8) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(8) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(8) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(8) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(8) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 9

```{r}
x_old <- x
cat("\nIteración 9\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(9) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(9) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(9) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(9) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(9) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(9) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 10

```{r}
x_old <- x
cat("\nIteración 10\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(10) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(10) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(10) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(10) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(10) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(10) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```

### Iteración 11

```{r}
x_old <- x
cat("\nIteración 11\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(11) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(11) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(11) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(11) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(11) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(11) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 12

```{r}
x_old <- x
cat("\nIteración 12\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(12) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(12) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(12) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(12) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(12) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(12) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 13

```{r}
x_old <- x
cat("\nIteración 13\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(13) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(13) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(13) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(13) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(13) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(13) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 14

```{r}
x_old <- x
cat("\nIteración 14\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(14) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(14) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(14) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(14) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(14) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(14) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 15

```{r}
x_old <- x
cat("\nIteración 15\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(15) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(15) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(15) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(15) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(15) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(15) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 16

```{r}
x_old <- x
cat("\nIteración 16\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(16) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(16) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(16) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(16) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(16) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(16) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 17

```{r}
x_old <- x
cat("\nIteración 17\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(17) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(17) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(17) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(17) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(17) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(17) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 18

```{r}
x_old <- x
cat("\nIteración 18\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(18) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(18) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(18) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(18) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(18) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(18) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 19

```{r}
x_old <- x
cat("\nIteración 19\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(19) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(19) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(19) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(19) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(19) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(19) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 20

```{r}
x_old <- x
cat("\nIteración 20\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(20) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(20) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(20) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(20) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(20) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(20) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 21

```{r}
x_old <- x
cat("\nIteración 21\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(21) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(21) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(21) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(21) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(21) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(21) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 22

```{r}
x_old <- x
cat("\nIteración 22\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(22) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(22) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(22) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(22) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(22) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(22) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 23

```{r}
x_old <- x
cat("\nIteración 23\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(23) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(23) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(23) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(23) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(23) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(23) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 24

```{r}
x_old <- x
cat("\nIteración 24\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(24) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(24) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(24) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(24) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(24) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(24) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


### Iteración 25

```{r}
x_old <- x
cat("\nIteración 25\n")
x[1] <- (b[1] + x_old[2]) / A[1,1]
cat(sprintf("x1^(25) = (1 + %g)/4 = %.8f\n", x_old[2], x[1]))
x[2] <- (b[2] + x[1] + x_old[3]) / A[2,2]
cat(sprintf("x2^(25) = (2 + %.8f + %g)/4 = %.8f\n", x[1], x_old[3], x[2]))
x[3] <- (b[3] + x[2] + x_old[4]) / A[3,3]
cat(sprintf("x3^(25) = (3 + %.8f + %g)/4 = %.8f\n", x[2], x_old[4], x[3]))
x[4] <- (b[4] + x[3] + x_old[5]) / A[4,4]
cat(sprintf("x4^(25) = (4 + %.8f + %g)/4 = %.8f\n", x[3], x_old[5], x[4]))
x[5] <- (b[5] + x[4]) / A[5,5]
cat(sprintf("x5^(25) = (5 + %.8f)/4 = %.8f\n", x[4], x[5]))
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(25) = %s\n", paste(sprintf("%.8f", x), collapse=", ")))
cat(sprintf("||dx||_inf = %.8e | ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


